services:
  seams-app:
    container_name: seams-app
    image: "begeospatial/seams-app:latest"
    volumes:
        # Add the local volume to the container
        - /home/begeospatial/develop/seams-app:/home/seams-app-user/seams-app
    user: "1000:1000"
    environment:
      - USER=seams-app-user
    ports:
      - "8501:8501"
    command:  streamlit run /home/seams-app-user/seams-app/seams_app/app.py 

