services:
  seams-app:
    container_name: seams-app
    image: "begeospatial/seams-app:latest"
    volumes:
      - seams-data-volume:/home/seams-app-user/seams-app/seams_app/data
      - <LOCALPATH_TO_SEAMS-APP_REPO>:/home/seams-app-user/seams-app
    user: "1000:1000"
    environment:
      - USER=seams-app-user
    ports:
      - "8501:8501"
    command:  streamlit run /home/seams-app-user/seams-app/seams_app/app.py 

volumes:
  seams-data-volume:
