[AFFILIATIONS]
SGU = "Sveriges Geologiska Undersökning"
ODF = "Ocean Data Factory - Sweden"
GU = "Göteborg University"
LU = "Lund University"
SMHI = "Sveriges Meteorologiska och Hydrologiska Institut"
SLU = "Sveriges Lantbruksuniversitet"
HaV = "Havs- och vattenmyndigheten"
BGS = "Be GeoSpatial"
Medins = "Medins Havs och Vattenkonsulter"
AQWR = "AquaBiota Water Research"