[LOGOS]
LOGO_SIDEBAR_URL = "sgu_seams_app/static/logos/sgu-logotype-blue-eng-489.png"
LOGO_ODF_URL = "sgu_seams_app/static/logos/ODF-logo.png"
LOGO_BEGEOSPATIAL = "sgu_seams_app/static/logos/Logo_BeGeoSpatial_black_landscape.png"