substrates = [
    ["Unknown Substrate", "UkSu"],
    ["Hard Clay", "HaCl"],
    ["Mud (<0.002mm)", "Mu"],
    ["Silt (0.002-0.06mm)", "Si"],
    ["Sand (0.06-2mm)", "Sa"],
    ["Gravel (2-20mm)", "Gr"],
    ["Stones/Pebbles (20-60mm)", "St"],
    ["Large Stones/Pebbles (60-200mm)", "LaSt"],
    ["Boulders (200-600mm)", "Bo"],
    ["Large Boulders (>600mm)", "LaBo"],
    ["Solid Rock", "SoRo"],
    ["Shell Gravel", "ShGr"],
    ["Coral", "C"]
]

commonLocations = [
    'Blekinge skg , Kalmarsund, inre,',
    'Blekinge skg , Kalmarsund, yttr,',
    'Bottenhavet,',
    'Bottenviken,',
    'Bottenviken, inre kustv.,',
    'Bottenviken, yttre kustv.,',
    'Gotlands västra , N kustv.,',
    'Göta Älvs , Nordre Älvs estuari,',
    'N Bottenhavet, Höga kusten, inr,',
    'N Bottenhavet, Höga kusten, ytt,',
    'N Kvarkens inre kustv.,',
    'N Kvarkens yttre kustv.,',
    'N Östersjön,',
    'Skånes kustv.,',
    'Stockh. inre skg , Hallsfjärden,',
    'Stockh. skg, yttre kustv.,',
    'Södra Bottenhavet, inre kustv.,',
    'Södra Bottenhavet, yttre kustv.,',
    'Södra Halland , N Öresunds kust,',
    'Södra Hallands , N Öresunds kus,',
    'Södra Östersjön,',
    'Västerhavet,',
    'Västkustens fjordar,',
    'Västkustens inre kustv., N,',
    'Västkustens inre kustv., södra,',
    'Västkustens yttre kustv., Katte,',
    'Västkustens yttre kustv., Skage,',
    'Öresunds kustv.,',
    'Österg. inre skg,',
    'Österg. samt Stockh. skg, mella,',
    'Österg. yttre kustv.,',
    'Östra Ölands, sydöstra Gotlands,']

USER_DEFINED_TAXONS =  {
    "Algae SFLAG FF",
    "Algae SFLAG FF STRID 5",
    "Algae SFLAG FF,UA",
    "Balanus SFLAG SPP",
    "Chara SFLAG SP",
    "Chlorophyceae SFLAG FF",
    "Chlorophyceae SFLAG FF STRID 5",
    "Chlorophyceae SFLAG FF,UA",
    "Cladophora SFLAG SPP",
    "Desmarestia SFLAG SPP",
    "Dictyosiphon/Stictyosiphon STRID 5",
    "Ectocarpus/Pylaiella STRID 5",
    "Fontinalis SFLAG SPP",
    "Fucus serratus SFLAG UA",
    "Fucus SFLAG SP",
    "Fucus vesiculosus SFLAG UA",
    "Gastropoda STAGE EG",
    "Gobius SFLAG SPP",
    "Henricia SFLAG SP",
    "Littorina SFLAG SPP",
    "Monia SFLAG SPP",
    "Myriophyllum SFLAG SPP",
    "Nassarius SFLAG SP",
    "Ophiura SFLAG SP",
    "Palaemon SFLAG SP",
    "Phaeophyceae SFLAG FF",
    "Phaeophyceae SFLAG FF STRID 5",
    "Phaeophyceae SFLAG FF,UA",
    "Pisces SFLAG SPP",
    "Plantae SFLAG FC",
    "Plantae SFLAG FF",
    "Plantae SFLAG FF,UA",
    "Plantae SFLAG FO",
    "Plantae SFLAG SC",
    "Plantae SFLAG UA",
    "Polymastia SFLAG SP",
    "Praunus SFLAG SPP",
    "Ranunculus SFLAG SPP",
    "Rhodophyta SFLAG FC",
    "Rhodophyta SFLAG FF",
    "Rhodophyta SFLAG FF STRID 5",
    "Rhodophyta SFLAG FF,UA",
    "Rhodophyta STRID 6",
    "Rhodyphyta SFLAG FC STRID 5",
    "Rhodyphyta SFLAG FC STRID 6",
    "Rhodyphyta SFLAG FF",
    "Rhodyphyta SFLAG FF STRID 6",
    "Rhodyphyta SFLAG FO",
    "Rissoa SFLAG SPP",
    "Ruppia SFLAG SP",
    "Sparganium SFLAG SP",
    "Sphacelaria SFLAG SPP",
    "Spirogyra SFLAG SP",
    "Ulva SFLAG SPP",
    "Urticina SFLAG SP",
    "Vaucheria SFLAG SPP",
    "Virgularia SFLAG SP",
}

# Stratum ID codes for the SMHI EPIBENTHOS DROPVIDEO
# http://www.smhi.se/polopoly_fs/1.116493!/Formatmall_Dropvideo.xlsx

STRATUM_ID = {
    'URL': 'http://www.smhi.se/polopoly_fs/1.116493!/Formatmall_Dropvideo.xlsx',
    'CODE': {
        'STRID 6': 'Drifting - algae detached from the substrate', 
        'STRID 5': 'Epiphytic - grows on another organism'}}

SPECIES_FLAGS = {
    'URL': 'http://www.smhi.se/polopoly_fs/1.116493!/Formatmall_Dropvideo.xlsx',
    'SFLAG': {
        'SP': 'A species within the genus.',
        'SPP': 'Several species within the genus.', 
        'FF':  'Filamentous fine | Filamentous algae (e.g. Cladophora spp., Pylaiella, Callithamnion, Aglaothamnion).',
        'FF,UA': 'Filamentous fine & Unattached (e.g. Cladophora spp., Pylaiella sp., Clorophyta, Rhodophyta, Phaeophyta).',
        'FC':  'Filamentous coarse | Finger-branched algae (e.g. Cystoclonium, Rhodomela, Desmarestia, Polysiphonia elongata).',
        'UA':  'Unattached | Free-living algae, (e.g. Cladophora, Pylaiella, Fucus serratus, Fucus vesiculosus, Ulva spp).',
        'FO':  'Foliose | Leafy (e.g. Coccothylus, Phyllophora, Phycodrus).',
        }
    }

OTHER_BENTHOS_COVER_OR_BIOTURBATION = {
    "COVER_DETRITUS",
    "COVER_EPI_ZOSTERA",
    "COVER_UNIDENT_PLANTAE",
    "COVER_NASSARIUS_TRACKS",
    "COVER_PAGURIDAE_TRACKS",
    "COVER_ANIMALIA_BURROWS",
    "COVER_ANIMALIA_TRACKS",
    "COVER_UNIDENTIFIED_ALGAE",
    "COVER_UNANALYSABLE"
}


phytobenthosCommonTaxa = {'Abra alba': {'commonLocation': ['Västkustens inre kustv., södra',
   'Öresunds kustv.']},
 'Abra nitida': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.']},
 'Actinopterygii': {'commonLocation': ['N Östersjön']},
 'Aegagropila linnaei': {'commonLocation': ['Bottenviken',
   'N Kvarkens yttre kustv.',
   'Österg. inre skg']},
 'Aglaothamnion roseum': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr']},
 'Agonus cataphractus': {'commonLocation': ['Södra Hallands , N Öresunds kus']},
 'Ahnfeltia plicata': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus']},
 'Alca torda': {'commonLocation': ['Bottenviken']},
 'Alcyonium digitatum': {'commonLocation': ['Västerhavet',
   'Västkustens yttre kustv., Skage']},
 'Algae': {'commonLocation': ['Södra Bottenhavet, inre kustv.']},
 'Ampelisca tenuicornis': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västkustens fjordar',
   'Västkustens inre kustv., N']},
 'Ampharete baltica': {'commonLocation': ['Södra Östersjön',
   'Västkustens inre kustv., södra',
   'Öresunds kustv.']},
 'Amphibalanus improvisus': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'Gotlands västra , N kustv.',
   'Göta Älvs , Nordre Älvs estuari',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Öresunds kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Amphipoda': {'commonLocation': ['Bottenviken', 'N Östersjön']},
 'Amphiura': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Amphiura chiajei': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Amphiura filiformis': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.']},
 'Ampullaceana balthica': {'commonLocation': ['N Bottenhavet, Höga kusten, ytt',
   'N Östersjön',
   'Östra Ölands, sydöstra Gotlands']},
 'Anguilla anguilla': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra']},
 'Animalia': {'commonLocation': ['Bottenviken']},
 'Anobothrus gracilis': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet',
   'Västkustens fjordar',
   'Öresunds kustv.']},
 'Anodonta': {'commonLocation': ['N Kvarkens inre kustv.']},
 'Arctica islandica': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus']},
 'Arenicola marina': {'commonLocation': ['Västkustens inre kustv., södra']},
 'Aricidea cerrutii': {'commonLocation': ['Öresunds kustv.']},
 'Asterias rubens': {'commonLocation': ['Södra Hallands , N Öresunds kus',
   'Västerhavet',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.']},
 'Astropecten irregularis': {'commonLocation': ['Västerhavet']},
 'Aurelia aurita': {'commonLocation': ['Gotlands västra , N kustv.']},
 'Bacillariophyceae': {'commonLocation': ['N Kvarkens yttre kustv.']},
 'Bacillariophyta': {'commonLocation': ['Bottenviken',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Kvarkens yttre kustv.']},
 'Bacteria': {'commonLocation': ['Stockh. skg, yttre kustv.',
   'Österg. inre skg']},
 'Balanus': {'commonLocation': ['Bottenhavet',
   'Gotlands västra , N kustv.',
   'Göta Älvs , Nordre Älvs estuari']},
  'Bare substrate': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Bottenviken, yttre kustv.',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Östersjön',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Bathyporeia pilosa': {'commonLocation': ['Skånes kustv.',
   'Södra Östersjön']},
 'Battersia': {'commonLocation': ['Södra Östersjön']},
 'Battersia arctica': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Bottenviken, yttre kustv.',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Östersjön',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Beggiatoa': {'commonLocation': ['Stockh. inre skg , Hallsfjärden',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Bithynia tentaculata': {'commonLocation': ['Stockh. inre skg , Hallsfjärden']},
 'Bolboschoenus maritimus': {'commonLocation': ['Stockh. inre skg , Hallsfjärden']},
 'Bonnemaisonia hamifera': {'commonLocation': ['Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Brada villosa': {'commonLocation': ['Södra Halland , N Öresunds kust']},
 'Brissopsis lyrifera': {'commonLocation': ['Västerhavet',
   'Västkustens yttre kustv., Skage']},
 'Brongniartella byssoides': {'commonLocation': ['Södra Hallands , N Öresunds kus',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Bryozoa': {'commonLocation': ['Bottenhavet',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, yttre kustv.']},
 'Bylgides sarsi': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'N Östersjön',
   'Stockh. skg, yttre kustv.',
   'Södra Östersjön',
   'Österg. yttre kustv.']},
 'Calliopius laeviusculus': {'commonLocation': ['Östra Ölands, sydöstra Gotlands']},
 'Callitriche': {'commonLocation': ['Bottenviken, inre kustv.']},
 'Callitriche hermaphroditica': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. samt Stockh. skg, mella']},
 'Cancer pagurus': {'commonLocation': ['Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Capitella capitata': {'commonLocation': ['Öresunds kustv.']},
 'Carcinus maenas': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.']},
 'Caryophyllia smithii': {'commonLocation': ['Västerhavet',
   'Västkustens yttre kustv., Skage']},
 'Ceramium': {'commonLocation': ['Gotlands västra , N kustv.',
   'Stockh. skg, yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Ceramium tenuicorne': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenviken',
   'Gotlands västra , N kustv.',
   'Göta Älvs , Nordre Älvs estuari',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Ceramium virgatum': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Göta Älvs , Nordre Älvs estuari',
   'Skånes kustv.',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Cerastoderma': {'commonLocation': ['Stockh. skg, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Cerastoderma glaucum': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'Skånes kustv.',
   'Öresunds kustv.',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Ceratophyllum demersum': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Chaetoderma nitidulum': {'commonLocation': ['Södra Halland , N Öresunds kust']},
 'Chaetomorpha linum': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Österg. inre skg']},
 'Chaetomorpha melagonium': {'commonLocation': ['Södra Hallands , N Öresunds kus',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Chaetozone setosa': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Halland , N Öresunds kust',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N']},
 'Chara': {'commonLocation': ['N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.']},
 'Chara aspera': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Chara baltica': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Chara canescens': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Stockh. skg, yttre kustv.']},
 'Chara globularis': {'commonLocation': ['Bottenviken, yttre kustv.',
   'N Kvarkens inre kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Österg. samt Stockh. skg, mella']},
 'Chara tomentosa': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Characeae': {'commonLocation': ['N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.']},
 'Chironomidae': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenviken',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Chironomus plumosus': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Södra Bottenhavet, inre kustv.']},
 'Chlorophyceae': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'Bottenviken, yttre kustv.']},
 'Chlorophyta': {'commonLocation': ['Gotlands västra , N kustv.',
   'Österg. inre skg']},
 'Chondrus crispus': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Hallands , N Öresunds kus',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Chorda': {'commonLocation': ['Södra Halland , N Öresunds kust']},
 'Chorda filum': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Skage',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Cladophora': {'commonLocation': ['Bottenviken',
   'Bottenviken, yttre kustv.',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Cladophora fracta': {'commonLocation': ['Österg. samt Stockh. skg, mella']},
 'Cladophora glomerata': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenviken',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Cladophora rupestris': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'Göta Älvs , Nordre Älvs estuari',
   'N Bottenhavet, Höga kusten, ytt',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Hallands , N Öresunds kus',
   'Östra Ölands, sydöstra Gotlands']},
 'Clupea harengus': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Östersjön',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Östra Ölands, sydöstra Gotlands']},
 'Coccotylus truncatus': {'commonLocation': ['Stockh. skg, yttre kustv.',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Coccotylus/Phyllophora': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Östersjön',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Corallina officinalis': {'commonLocation': ['Västkustens inre kustv., N',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Corbula gibba': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.']},
 'Cordylophora caspia': {'commonLocation': ['Bottenviken',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Östersjön']},
 'Corophium volutator': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'N Kvarkens inre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Österg. inre skg',
   'Östra Ölands, sydöstra Gotlands']},
 'Cottidae': {'commonLocation': ['Bottenhavet']},
 'Crangon crangon': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Västkustens inre kustv., södra',
   'Öresunds kustv.']},
 'Ctenolabrus rupestris': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Cyanobacteria': {'commonLocation': ['Bottenviken', 'Österg. inre skg']},
 'Cyanophthalma obscura': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Östersjön',
   'Stockh. inre skg , Hallsfjärden',
   'Östra Ölands, sydöstra Gotlands']},
 'Cyathura carinata': {'commonLocation': ['Öresunds kustv.']},
 'Cylichna cylindracea': {'commonLocation': ['Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens yttre kustv., Katte']},
 'Cystoclonium purpureum': {'commonLocation': ['Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Delesseria sanguinea': {'commonLocation': ['Södra Hallands , N Öresunds kus',
   'Västkustens inre kustv., N',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Diastylis lucifera': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet']},
 'Diastylis rathkei': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Öresunds kustv.']},
 'Diatoma': {'commonLocation': ['N Kvarkens yttre kustv.']},
 'Dictyosiphon foeniculaceus': {'commonLocation': ['N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Dictyosiphon/Stictyosiphon': {'commonLocation': ['N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt']},
 'Diplocirrus glaucus': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Halland , N Öresunds kust',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Dipolydora quadrilobata': {'commonLocation': ['Öresunds kustv.']},
 'Ectocarpus/Pylaiella': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Östra Ölands, sydöstra Gotlands']},
 'Einhornia crustulenta': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Elachista': {'commonLocation': ['Gotlands västra , N kustv.']},
 'Elachista fucicola': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, ytt',
   'Skånes kustv.']},
 'Elatine': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Kvarkens inre kustv.']},
 'Elatine hydropiper': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Kvarkens inre kustv.']},
 'Electra': {'commonLocation': ['Bottenhavet', 'Södra Östersjön']},
 'Electra pilosa': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Skånes kustv.']},
 'Eleocharis': {'commonLocation': ['Bottenviken, yttre kustv.',
   'N Kvarkens yttre kustv.']},
 'Eleocharis acicularis': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.']},
 'Elodea': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.']},
 'Elodea canadensis': {'commonLocation': ['Bottenviken, inre kustv.',
   'N Kvarkens inre kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Österg. inre skg']},
 'Ennucula tenuis': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet',
   'Västkustens fjordar']},
 'Ephydatia fluviatilis': {'commonLocation': ['Bottenviken',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.']},
 'Esox lucius': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Skånes kustv.',
   'Österg. inre skg']},
 'Eteone longa': {'commonLocation': ['Öresunds kustv.']},
 'Eudorella emarginata': {'commonLocation': ['Västerhavet']},
 'Flustra foliacea': {'commonLocation': ['Västkustens yttre kustv., Skage']},
 'Fontinalis': {'commonLocation': ['Bottenviken, inre kustv.',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'Södra Bottenhavet, yttre kustv.']},
 'Fontinalis dalecarlica': {'commonLocation': ['Södra Bottenhavet, yttre kustv.']},
 'Fucus': {'commonLocation': ['Bottenhavet',
   'N Bottenhavet, Höga kusten, ytt',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Halland , N Öresunds kust']},
 'Fucus radicans': {'commonLocation': ['N Bottenhavet, Höga kusten, ytt',
   'N Östersjön',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.']},
 'Fucus serratus': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Göta Älvs , Nordre Älvs estuari',
   'Skånes kustv.',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Skage',
   'Östra Ölands, sydöstra Gotlands']},
 'Fucus vesiculosus': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Gotlands västra , N kustv.',
   'Göta Älvs , Nordre Älvs estuari',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Västkustens inre kustv., södra',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Furcellaria': {'commonLocation': ['Bottenhavet']},
 'Furcellaria lumbricalis': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Gotlands västra , N kustv.',
   'Göta Älvs , Nordre Älvs estuari',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Gadus morhua': {'commonLocation': ['Bottenhavet',
   'Göta Älvs , Nordre Älvs estuari',
   'Skånes kustv.',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Östra Ölands, sydöstra Gotlands']},
 'Galathowenia oculata': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Halland , N Öresunds kust',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., södra',
   'Öresunds kustv.']},
 'Gammarus': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Bottenviken, inre kustv.',
   'N Bottenhavet, Höga kusten, ytt',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Östersjön',
   'Öresunds kustv.',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Gammarus oceanicus': {'commonLocation': ['Östra Ölands, sydöstra Gotlands']},
 'Gammarus salinus': {'commonLocation': ['N Östersjön',
   'Stockh. inre skg , Hallsfjärden',
   'Östra Ölands, sydöstra Gotlands']},
 'Gammarus zaddachi': {'commonLocation': ['Bottenhavet']},
 'Gasterosteus aculeatus': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.']},
 'Glycera alba': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens yttre kustv., Katte']},
 'Glycera unicornis': {'commonLocation': ['Västerhavet']},
 'Gobius niger': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Göta Älvs , Nordre Älvs estuari',
   'Stockh. skg, yttre kustv.',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Österg. samt Stockh. skg, mella']},
 'Gobiusculus flavescens': {'commonLocation': ['Gotlands västra , N kustv.']},
 'Goniada maculata': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Gymnocephalus cernuus': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Bottenviken',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella']},
 'Halichondria panicea': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari']},
 'Halicryptus spinulosus': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'N Östersjön',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Östersjön',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Halidrys siliquosa': {'commonLocation': ['Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Halosiphon tomentosus': {'commonLocation': ['N Östersjön']},
 'Harmothoe impar': {'commonLocation': ['Öresunds kustv.']},
 'Hediste diversicolor': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'Göta Älvs , Nordre Älvs estuari',
   'Skånes kustv.',
   'Södra Östersjön',
   'Öresunds kustv.',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Heteromastus filiformis': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Hallands , N Öresunds kus',
   'Västerhavet',
   'Västkustens fjordar',
   'Öresunds kustv.']},
 'Hildenbrandia': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Södra Östersjön',
   'Österg. inre skg']},
 'Hildenbrandia rubra': {'commonLocation': ['Bottenhavet',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus']},
 'Hyala vitrea': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Hydrobia': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Östersjön',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Hydrobiidae': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'N Östersjön',
   'Skånes kustv.']},
 'Hydroidolina': {'commonLocation': ['Bottenhavet',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.']},
 'Hydrozoa': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'Bottenviken, yttre kustv.',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Östersjön',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Östersjön',
   'Österg. inre skg',
   'Österg. yttre kustv.']},
 'Idotea': {'commonLocation': ['Östra Ölands, sydöstra Gotlands']},
 'Idotea balthica': {'commonLocation': ['Östra Ölands, sydöstra Gotlands']},
 'Idotea chelipes': {'commonLocation': ['Östra Ölands, sydöstra Gotlands']},
 'Isoëtes echinospora': {'commonLocation': ['N Kvarkens inre kustv.']},
 'Jaera albifrons': {'commonLocation': ['N Östersjön',
   'Stockh. inre skg , Hallsfjärden',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Kurtiella bidentata': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.']},
 'Labidoplax buskii': {'commonLocation': ['Södra Halland , N Öresunds kust']},
 'Labrus bergylta': {'commonLocation': ['Västkustens inre kustv., N']},
 'Laminaria digitata': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Laminaria hyperborea': {'commonLocation': ['Västkustens yttre kustv., Skage']},
 'Lemna trisulca': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.']},
 'Leucon (Leucon) nasica': {'commonLocation': ['Västerhavet']},
 'Levinsenia gracilis': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Halland , N Öresunds kust',
   'Öresunds kustv.']},
 'Limapontia capitata': {'commonLocation': ['Östra Ölands, sydöstra Gotlands']},
 'Limecola balthica': {'commonLocation': ['Bottenhavet',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Östersjön',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Östersjön']},
 'Limnodrilus': {'commonLocation': ['Bottenviken, inre kustv.']},
 'Lithothamnion/Phymatolithon': {'commonLocation': ['Västkustens fjordar',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Lymnaea': {'commonLocation': ['Bottenhavet', 'Bottenviken']},
 'Macoma balthica': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Östersjön',
   'Öresunds kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Macoma calcarea': {'commonLocation': ['Öresunds kustv.']},
 'Maldane sarsi': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet']},
 'Marenzelleria': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Bottenviken, yttre kustv.',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Östersjön',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Marenzelleria neglecta': {'commonLocation': ['Bottenhavet',
   'N Bottenhavet, Höga kusten, inr',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.']},
 'Marenzelleria viridis': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.']},
 'Marthasterias glacialis': {'commonLocation': ['Västerhavet',
   'Västkustens yttre kustv., Skage']},
 'Membranipora membranacea': {'commonLocation': ['Skånes kustv.']},
 'Merlangius merlangus': {'commonLocation': ['Västkustens inre kustv., N',
   'Västkustens inre kustv., södra']},
 'Microdeutopus': {'commonLocation': ['Öresunds kustv.']},
 'Microtendipes pedellus': {'commonLocation': ['Bottenviken, inre kustv.']},
 'Micrura baltica': {'commonLocation': ['N Östersjön']},
 'Mollusca': {'commonLocation': ['Gotlands västra , N kustv.', 'N Östersjön']},
 'Monodiamesa': {'commonLocation': ['Bottenviken, inre kustv.']},
 'Monoporeia affinis': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Östersjön',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Monostroma balticum': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Stockh. skg, yttre kustv.',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Mya arenaria': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'Skånes kustv.',
   'Södra Östersjön',
   'Öresunds kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Myoxocephalus scorpius': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'Göta Älvs , Nordre Älvs estuari',
   'Skånes kustv.',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte']},
 'Myriophyllum': {'commonLocation': ['Bottenviken, yttre kustv.',
   'N Kvarkens yttre kustv.',
   'Österg. inre skg']},
 'Myriophyllum alterniflorum': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Kvarkens inre kustv.',
   'Södra Bottenhavet, yttre kustv.']},
 'Myriophyllum sibiricum': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. samt Stockh. skg, mella']},
 'Myriophyllum spicatum': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Mysidae': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Österg. inre skg']},
 'Mysis mixta': {'commonLocation': ['Bottenhavet', 'N Östersjön']},
 'Mysis relicta': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'N Bottenhavet, Höga kusten, inr',
   'N Östersjön',
   'Stockh. inre skg , Hallsfjärden']},
 'Mysis relicta s.lat.': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'N Östersjön']},
 'Mytilus': {'commonLocation': ['Bottenhavet']},
 'Mytilus edulis': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Gotlands västra , N kustv.',
   'Göta Älvs , Nordre Älvs estuari',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Halland , N Öresunds kust',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Öresunds kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Myxine glutinosa': {'commonLocation': ['Västerhavet']},
 'Najas marina': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Nematoda': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'Bottenviken, inre kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Öresunds kustv.']},
 'Nemertea': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'N Östersjön',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.']},
 'Neogobius melanostomus': {'commonLocation': ['Gotlands västra , N kustv.']},
 'Nephrops norvegicus': {'commonLocation': ['Västerhavet']},
 'Nephtys ciliata': {'commonLocation': ['Öresunds kustv.']},
 'Nephtys hombergii': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västkustens inre kustv., södra',
   'Öresunds kustv.']},
 'Nephtys incisa': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Nitella flexilis': {'commonLocation': ['Bottenviken, yttre kustv.']},
 'Nitella flexilis/opaca': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.']},
 'Nitella flexilis/opaca ': {'commonLocation': ['Bottenviken, yttre kustv.']},
 'Nucula nitidosa': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra']},
 'Oligochaeta': {'commonLocation': ['Bottenviken',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Östersjön',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.']},
 'Ophiocomina nigra': {'commonLocation': ['Västerhavet']},
 'Ophiothrix fragilis': {'commonLocation': ['Västerhavet']},
 'Ophiura': {'commonLocation': ['Öresunds kustv.']},
 'Ophiura albida': {'commonLocation': ['Södra Halland , N Öresunds kust']},
 'Osteichthyes': {'commonLocation': ['Bottenviken', 'N Östersjön']},
 'Ostracoda': {'commonLocation': ['Bottenhavet']},
 'Ostrea edulis': {'commonLocation': ['Västkustens inre kustv., N']},
 'Oxydromus flexuosus': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet',
   'Västkustens fjordar']},
 'Paguridae': {'commonLocation': ['Västerhavet']},
 'Pagurus': {'commonLocation': ['Södra Hallands , N Öresunds kus',
   'Västerhavet']},
 'Pagurus bernhardus': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet',
   'Västkustens inre kustv., N']},
 'Palaemon': {'commonLocation': ['Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra']},
 'Palaemon adspersus': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari']},
 'Pallaseopsis quadrispinosa': {'commonLocation': ['Bottenviken, inre kustv.']},
 'Parathyasira equalis': {'commonLocation': ['Västerhavet']},
 'Pectinaria auricoma': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet',
   'Västkustens yttre kustv., Katte']},
 'Pectinaria belgica': {'commonLocation': ['Västerhavet']},
 'Pectinaria koreni': {'commonLocation': ['Öresunds kustv.']},
 'Pennatula': {'commonLocation': ['Västerhavet']},
 'Pennatula phosphorea': {'commonLocation': ['Västerhavet']},
 'Perca fluviatilis': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Östra Ölands, sydöstra Gotlands']},
 'Peregriana labiata': {'commonLocation': ['N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens yttre kustv.']},
 'Peringia ulvae': {'commonLocation': ['Öresunds kustv.']},
 'Phaeophyceae': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'Gotlands västra , N kustv.',
   'N Östersjön',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Halland , N Öresunds kust',
   'Österg. inre skg']},
 'Phaxas pellucidus': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Västkustens inre kustv., södra']},
 'Philine quadripartita': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Västkustens fjordar',
   'Västkustens inre kustv., södra']},
 'Phoca vitulina': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari']},
 'Pholoe baltica': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.']},
 'Pholoe pallida': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet']},
 'Phoronis muelleri': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.']},
 'Phragmites australis': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella']},
 'Phycodrys rubens': {'commonLocation': ['Södra Hallands , N Öresunds kus',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Phyllodoce groenlandica': {'commonLocation': ['Öresunds kustv.']},
 'Phyllophora pseudoceranoïdes': {'commonLocation': ['Gotlands västra , N kustv.',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Pisidium': {'commonLocation': ['Bottenviken, inre kustv.']},
 'Plantae': {'commonLocation': ['Gotlands västra , N kustv.']},
 'Platichthys flesus': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Bottenhavet',
   'Gotlands västra , N kustv.',
   'Skånes kustv.',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Österg. samt Stockh. skg, mella',
   'Östra Ölands, sydöstra Gotlands']},
 'Pleuronectes platessa': {'commonLocation': ['Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra']},
 'Podocoryna carnea': {'commonLocation': ['Västkustens inre kustv., södra']},
 'Pollachius pollachius': {'commonLocation': ['Västkustens inre kustv., N']},
 'Pollachius virens': {'commonLocation': ['Södra Hallands , N Öresunds kus',
   'Västkustens inre kustv., N']},
 'Polypedilum': {'commonLocation': ['Bottenviken, inre kustv.']},
 'Polysiphonia': {'commonLocation': ['Gotlands västra , N kustv.',
   'Stockh. skg, yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Polysiphonia fibrillosa': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Göta Älvs , Nordre Älvs estuari',
   'Skånes kustv.',
   'Österg. inre skg']},
 'Polysiphonia fucoides': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'Göta Älvs , Nordre Älvs estuari',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens yttre kustv., Katte',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Polysiphonia/Rhodomela confervoides': {'commonLocation': ['Södra Östersjön']},
 'Pomatoschistus': {'commonLocation': ['Gotlands västra , N kustv.',
   'Österg. inre skg']},
 'Pomatoschistus minutus': {'commonLocation': ['Bottenviken',
   'Österg. inre skg']},
 'Pontoporeia femorata': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'N Östersjön',
   'Stockh. skg, yttre kustv.',
   'Södra Östersjön',
   'Österg. yttre kustv.']},
 'Porifera': {'commonLocation': ['Bottenviken',
   'Bottenviken, yttre kustv.',
   'N Kvarkens yttre kustv.']},
 'Potamogeton': {'commonLocation': ['Österg. yttre kustv.']},
 'Potamogeton berchtoldii': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.']},
 'Potamogeton crispus': {'commonLocation': ['Stockh. inre skg , Hallsfjärden',
   'Österg. inre skg']},
 'Potamogeton gramineus': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.']},
 'Potamogeton perfoliatus': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Potamogeton pusillus': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Södra Bottenhavet, yttre kustv.']},
 'Potamopyrgus antipodarum': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenviken, inre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.',
   'Österg. samt Stockh. skg, mella']},
 'Potamothrix hammoniensis': {'commonLocation': ['Bottenviken, inre kustv.']},
 'Praunus inermis': {'commonLocation': ['Östra Ölands, sydöstra Gotlands']},
 'Priapulus caudatus': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Västkustens fjordar',
   'Öresunds kustv.']},
 'Prionospio fallax': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte']},
 'Procladius': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'Södra Bottenhavet, inre kustv.']},
 'Pseudolithoderma': {'commonLocation': ['Bottenviken',
   'N Kvarkens yttre kustv.',
   'N Östersjön']},
 'Pseudolithoderma extensum': {'commonLocation': ['Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Pterothamnion plumula': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Västkustens yttre kustv., Skage']},
 'Pygospio elegans': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'N Östersjön',
   'Skånes kustv.',
   'Södra Östersjön',
   'Öresunds kustv.',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Pylaiella': {'commonLocation': ['Bottenhavet',
   'Gotlands västra , N kustv.']},
 'Pylaiella littoralis': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Södra Östersjön',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Ranunculus baudotii': {'commonLocation': ['N Kvarkens yttre kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Ranunculus circinatus': {'commonLocation': ['Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella']},
 'Ranunculus confervoides': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.']},
 'Ranunculus peltatus': {'commonLocation': ['N Kvarkens inre kustv.',
   'Österg. inre skg']},
 'Ranunculus peltatus agg.': {'commonLocation': ['N Kvarkens inre kustv.',
   'Stockh. inre skg , Hallsfjärden']},
 'Retusa obtusa': {'commonLocation': ['Öresunds kustv.']},
 'Rhodine gracilior': {'commonLocation': ['Öresunds kustv.']},
 'Rhodine loveni': {'commonLocation': ['Västerhavet']},
 'Rhodochorton': {'commonLocation': ['Bottenhavet']},
 'Rhodochorton purpureum': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'N Bottenhavet, Höga kusten, ytt',
   'Stockh. skg, yttre kustv.']},
 'Rhodomela': {'commonLocation': ['Gotlands västra , N kustv.']},
 'Rhodomela confervoides': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, ytt',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens yttre kustv., Katte',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Rhodophyta': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Gotlands västra , N kustv.',
   'N Östersjön',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västerhavet',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Rivularia atra': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'N Bottenhavet, Höga kusten, ytt',
   'Södra Bottenhavet, yttre kustv.']},
 'Ruppia': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Ruppia maritima': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Skånes kustv.',
   'Stockh. skg, yttre kustv.',
   'Västkustens inre kustv., södra',
   'Östra Ölands, sydöstra Gotlands']},
 'Ruppia spiralis': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Skånes kustv.',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Rutilus rutilus': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Bottenviken',
   'Bottenviken, inre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella']},
 'Saccharina latissima': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Halland , N Öresunds kust',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Saduria entomon': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenhavet',
   'Bottenviken',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Östersjön',
   'Österg. inre skg',
   'Österg. yttre kustv.']},
 'Sagittaria': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Kvarkens inre kustv.']},
 'Scalibregma inflatum': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Hallands , N Öresunds kus',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.']},
 'Schoenoplectus tabernaemontani': {'commonLocation': ['Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.']},
 'Scoloplos armiger': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Öresunds kustv.']},
 'Scophthalmus maximus': {'commonLocation': ['Södra Östersjön',
   'Östra Ölands, sydöstra Gotlands']},
 'Solea solea': {'commonLocation': ['Södra Hallands , N Öresunds kus']},
 'Somateria mollissima': {'commonLocation': ['Bottenviken',
   'Gotlands västra , N kustv.']},
 'Sparganium': {'commonLocation': ['Bottenviken, inre kustv.']},
 'Sphacelaria': {'commonLocation': ['Bottenhavet',
   'N Bottenhavet, Höga kusten, ytt',
   'Stockh. skg, yttre kustv.']},
 'Spinachia spinachia': {'commonLocation': ['Södra Östersjön']},
 'Spionidae': {'commonLocation': ['Södra Östersjön']},
 'Spiophanes kroeyeri': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens yttre kustv., Skage']},
 'Spirulina': {'commonLocation': ['Stockh. skg, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Stictyosiphon tortilis': {'commonLocation': ['N Bottenhavet, Höga kusten, ytt',
   'Stockh. skg, yttre kustv.']},
 'Stuckenia filiformis': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.']},
 'Stuckenia pectinata': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Stylatula elegans': {'commonLocation': ['Västerhavet']},
 'Subularia aquatica': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.']},
 'Symphodus melops': {'commonLocation': ['Södra Hallands , N Öresunds kus',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage']},
 'Tanytarsus': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.']},
 'Taurulus bubalis': {'commonLocation': ['Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra']},
 'Terebellides stroemii': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'N Östersjön',
   'Södra Halland , N Öresunds kust',
   'Södra Östersjön',
   'Västerhavet',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.']},
 'Theodoxus fluviatilis': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Bottenviken',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens yttre kustv.',
   'N Östersjön',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Thyasira flexuosa': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Öresunds kustv.']},
 'Tolypella nidifica': {'commonLocation': ['Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Österg. samt Stockh. skg, mella']},
 'Tritia nitida': {'commonLocation': ['Göta Älvs , Nordre Älvs estuari',
   'Västkustens inre kustv., södra',
   'Öresunds kustv.']},
 'Trochochaeta multisetosa': {'commonLocation': ['Öresunds kustv.']},
 'Turritella communis': {'commonLocation': ['Västkustens yttre kustv., Katte']},
 'Typha angustifolia': {'commonLocation': ['Stockh. inre skg , Hallsfjärden']},
 'Ulva': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Västkustens inre kustv., södra',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.']},
 'Ulva intestinalis': {'commonLocation': ['Blekinge skg , Kalmarsund, yttr',
   'Göta Älvs , Nordre Älvs estuari']},
 'Ulvaria splendens': {'commonLocation': ['Stockh. inre skg , Hallsfjärden']},
 'Uria aalge': {'commonLocation': ['Bottenviken']},
 'Valvata piscinalis': {'commonLocation': ['Stockh. inre skg , Hallsfjärden']},
 'Vaucheria': {'commonLocation': ['Bottenviken, inre kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Södra Bottenhavet, inre kustv.',
   'Österg. inre skg']},
 'Vaucheriaceae': {'commonLocation': ['Bottenviken, yttre kustv.']},
 'Virgularia': {'commonLocation': ['Västerhavet']},
 'Virgularia mirabilis': {'commonLocation': ['Södra Halland , N Öresunds kust',
   'Västerhavet']},
 'Zannichellia': {'commonLocation': ['N Kvarkens yttre kustv.']},
 'Zannichellia palustris': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Bottenviken, inre kustv.',
   'Bottenviken, yttre kustv.',
   'Gotlands västra , N kustv.',
   'N Bottenhavet, Höga kusten, inr',
   'N Bottenhavet, Höga kusten, ytt',
   'N Kvarkens inre kustv.',
   'N Kvarkens yttre kustv.',
   'Skånes kustv.',
   'Stockh. inre skg , Hallsfjärden',
   'Stockh. skg, yttre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Österg. inre skg',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Zoarces viviparus': {'commonLocation': ['Bottenhavet',
   'Bottenviken',
   'Gotlands västra , N kustv.',
   'Göta Älvs , Nordre Älvs estuari',
   'N Kvarkens inre kustv.',
   'Södra Bottenhavet, inre kustv.',
   'Södra Bottenhavet, yttre kustv.',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra']},
 'Zostera': {'commonLocation': ['Västkustens fjordar']},
 'Zostera marina': {'commonLocation': ['Blekinge skg , Kalmarsund, inre',
   'Blekinge skg , Kalmarsund, yttr',
   'Göta Älvs , Nordre Älvs estuari',
   'Skånes kustv.',
   'Södra Halland , N Öresunds kust',
   'Södra Hallands , N Öresunds kus',
   'Södra Östersjön',
   'Västkustens fjordar',
   'Västkustens inre kustv., N',
   'Västkustens inre kustv., södra',
   'Västkustens yttre kustv., Katte',
   'Västkustens yttre kustv., Skage',
   'Öresunds kustv.',
   'Österg. samt Stockh. skg, mella',
   'Österg. yttre kustv.',
   'Östra Ölands, sydöstra Gotlands']},
 'Zostera noltii': {'commonLocation': ['Västkustens inre kustv., södra']}}